# readthedocs version
version: 2

build:
    image: latest

sphinx:
  builder: html
  configuration: docs/source/conf.py

conda:
  environment: environment.yaml

python:
    install:
        - method: pip
          path: .

